### ISSUE TITLE
Set up local environment

### ISSUE THREAD

**Issue by ltartari** [okfn-brasil/mosaico#1]
As a developer
I need to set up my local environment
So that I can start working.

In scope (aka Tech Stack)
- Language: Ruby 2
- Frameworks: AngularJS on Ruby on Rails (4)
- Abstractions: Coffeescript, Slim and Scss

Out of scope
- Database

**Comment by vitorbaptista** [comment]
I tried using Yeoman/Grunt/Bower, as we only use Rails for compiling coffeescript/slim/scss, but had no success.

Might be better this way, as we may need Rails to build a CMS later

**Comment by ltartari** [comment]
I would love to have Yeoman/Grunt/Bower, but due to the fact that we're dealing with a one pointer stick to our default stack : )

**Comment by vitorbaptista** [comment]
So we ended up ditching Rails and using Yeoman/Bower/Grunt to organize our workflow. For my part, this is done. After you, @ltartari, installs everything in your machine and checks that you're able to deploy, we can close this.

**Comment by ltartari** [comment]
Can I ask for a README file with step-by-step instructions?
![just-following-instructions](https://f.cloud.github.com/assets/114248/1070085/92cab888-1440-11e3-8881-996966ab93ae.gif)

**Comment by ltartari** [comment]
Ok, this is done. "Works on my machine" seal of approval.
