### ISSUE TITLE
Handle multiple values on Open Spending

### ISSUE THREAD

**Issue by ltartari** [okfn-brasil/mosaico#12]

**Comment by ltartari** [comment]
Waiting @vitorbaptista to talk with @tryggvib and see if it's possible to make this happen on Open Spending.

**Comment by vitorbaptista** [comment]
@tryggvib estimated this as one day. I'm all in for funding him to do it,
but it depends on our budget. @everton137?

**Comment by everton137** [comment]
@vitorbaptista included one day work of @tryggvib in the budget paid by OKF Brasil.

**Comment by vitorbaptista** [comment]
@tryggvib I don't know the details on how the budget will be transfered to you, but the sooner you can do this, the better. I'll have to keep doing the workaround while we don't have this functionality.

**Comment by trickvi** [comment]
@vitorbaptista I've created a [pull request](https://github.com/openspending/openspending/pull/682) on openspending with the fix. Could you review it? I'll deploy when it's reviewed and ready.

**Comment by vitorbaptista** [comment]
Great job, @tryggvib!

FYI, this patch is already done, merged and live in https://github.com/openspending/openspending/pull/682. You can check that it works going in http://openspending.org/api/2/aggregate?cut=time.year%3A2012%7Corgao%3A26000&dataset=orcamento_federal&drilldown=time.month&measure=pago|rppago|amount&order=time.month%3Aasc.

:beers:

**Comment by ltartari** [comment]
Great team work guys! ;-)
![team-work](https://f.cloud.github.com/assets/114248/1075184/22d2328e-14c9-11e3-823f-b5cf4d2dcba8.gif)
