### ISSUE TITLE
Treemap development

### ISSUE THREAD

**Issue by ltartari** [okfn-brasil/mosaico#13]
```
Função
  Subfunção
    Órgão
      Unidade Orçamentária
        Modalidade de Aplicação
          Elemento de Despesa
```

**Comment by ltartari** [comment]
@vitorbaptista there's a bug: when using the browser buttons to navigate I can't navigate using the treemap anymore. Happening in production. Do you think this should be logged as a new bug?

**Comment by vitorbaptista** [comment]
@ltartari Could you try this again? I couldn't reproduce it...

**Comment by ltartari** [comment]
@vitorbaptista yes, still happening. I can show you on skype…

**Comment by vitorbaptista** [comment]
IMO, it's done. The only thing missing is #36, but I don't think it blocks the card. :beers:

**Comment by ltartari** [comment]
Indeed! :cocktail: :cocktail:

**Comment by andressafioravanti** [comment]
Vitor, será possível diminuir a letra dos quadrados menores ( ou de todos os quadrados, se for a única opção) para que assim, mais quadrados tenham o nome identificado? acho que isso melhora o entendimento do treemap como um todo. 
Outra coisa, não entendi porque alguns quadrados onde nao cabem o nome dele, tem mesmo assim um pedaço do nome ( entenda por nome, a função, subf, orgão etc) e outros nao tem nem pedaço de nome. Dá pra regularizar isso? Tipo, ou cabe o nome todo ou nao escreve nada.

**Comment by ltartari** [comment]
@andressafioravanti Eu consigo alterar o tamanho da fonte para todos os nomes, mas para fazer aparecer nas áreas menores é outro departamento : ) É possível, @vitorbaptista ?

**Comment by vitorbaptista** [comment]
@andressafioravanti Diminuir a fonte como um todo é simples, como o @ltartari falou. Mas adicionar essa lógica de diminuir só nos quadrados menores não. Também não encontrei um exemplo de texto cortado, você pode passar o link?

**Comment by andressafioravanti** [comment]
http://weiss.herokuapp.com/#/treemap/2013/28-encargos-especiais/845-transferencias

**Comment by vitorbaptista** [comment]
@andressafioravanti A lógica que está feita é que se um quadradinho do treemap for maior que um valor percentual (no caso, 3%), mostra o texto. Se não, não. No que você linkou, o ministério das cidades tem 5,03%, por isso está aparecendo.

O que eu posso fazer é aumentar esse limiar para, por exemplo, 6%. Resolve no caso do link que você passou, mas pode ter algum outro lugar onde vai cortar também. Uma desvantagem é que no treemap de 2012, por exemplo, alguns quadradinhos que estavam com o texto bom, sem cortar, vão desaparecer. Por exemplo, com essa modificação para 6%, o treemap vira:

![image](https://f.cloud.github.com/assets/76945/1249488/570dea2e-2ae1-11e3-9765-e0e99380ec95.png)

Comparativamente, com os 3% (que é o atual), ele fica:

![image](https://f.cloud.github.com/assets/76945/1249496/7b0ca816-2ae1-11e3-8491-a6122f141891.png)

As duas soluções têm desvantagem. Realmente resolver esse problema é inviável no tempo que temos.

Qual você prefere?

**Comment by vitorbaptista** [comment]
@andressafioravanti Pra ficar mais fácil de comparar, mandei o código para staging. Você pode ver a diferença comparando com production. Por exemplo, http://weiss.herokuapp.com/#/treemap/2013/28-encargos-especiais/845-transferencias e http://weiss-staging.herokuapp.com/#/treemap/2013/28-encargos-especiais/845-transferencias.

Não liga para as cores ainda.

**Comment by andressafioravanti** [comment]
@vitorbaptista  Não dá pra mudar a posição da barra?
Se ela ficasse na horizontal caberia...

**Comment by vitorbaptista** [comment]
@andressafioravanti Caberia em alguns, mas não todos. Nos quadradinhos menores não tem como fazer, seja horizontal ou verticalmente. A solução é corrigir esse cálculo que diz se o texto cabe. A forma que está feita no OpenSpending (colocar em quadrados maiores que 3% do total) é super simples, mas tem essas falhas. Mudar isso não é fácil.

Posso criar uma issue para não esquecermos desse problema e, na extensão, estimá-lo e priorizá-lo junto com as outras coisas. Daí podemos resolver. O que você acha?

**Comment by andressafioravanti** [comment]
Acho melhor não aumentarmos a proporção para aparecer os nomes. Deixamos então como uma issue.

**Comment by vitorbaptista** [comment]
@andressafioravanti Criei a issue #44 para priorizarmos depois. Acho que isso era a única dúvida que bloqueava essa issue, certo? Se não houver mais nada, por favor, feche ela :+1:
