### ISSUE TITLE
Data grid below Treemap

### ISSUE THREAD

**Issue by ltartari** [okfn-brasil/mosaico#16]
Should show Treemap elements with "Empenhado" (Pago + RP Pago) values.

**Comment by vitorbaptista** [comment]
Should the label really be "Empenhado"? In the project with INESC, we called that "Pagamentos" (which I agree is a bit confusing. Without context, what's the difference between Pago and Pagamentos?)

**Comment by vitorbaptista** [comment]
@andressafioravanti Você pode confirmar que essa issue está completa e, se sim, fechá-la também?

**Comment by andressafioravanti** [comment]
amount,elemento_despesa.html_url,elemento_despesa.id,elemento_despesa.label,elemento_despesa.name,elemento_despesa.taxonomy,funcao.html_url,funcao.id,funcao.label,funcao.name,funcao.taxonomy,mod_aplic.html_url,mod_aplic.id,mod_aplic.label,mod_aplic.name,mod_aplic.taxonomy,num_entries,orgao.html_url,orgao.id,orgao.label,orgao.name,orgao.taxonomy,pago,rppago,subfuncao.html_url,subfuncao.id,subfuncao.label,subfuncao.name,subfuncao.taxonomy,uo.html_url,uo.id,uo.label,uo.name,uo.taxonomy

Abre no EXCEL um texto enorme no formato que eu colei aí, acho que deve ter algum erro

**Comment by vitorbaptista** [comment]
@andressafioravanti É que é um arquivo CSV. Não tenho o Excel para te ajudar, mas tem explicando como importar um arquivo CSV em http://office.microsoft.com/en-us/excel-help/import-or-export-text-txt-or-csv-files-HP010099725.aspx#BMimport_data_from_a_text_file_by_openi
