### ISSUE TITLE
Contextual data download button

### ISSUE THREAD

**Issue by ltartari** [okfn-brasil/mosaico#17]
Provide the ability to download a the data at any given application context, using the current navigation as a filter for creating this new smaller dataset.

**Comment by vitorbaptista** [comment]
There's "just" design work left on this. @ltartari I'm assigning you now

When you get to work on this and #15, tell me if you prefer to have a different text for each button, or it can be the same. I developed in a way that you can put whatever text you like in each of them, but if they're all the same, I could put in a single place to keep it DRY.
