### ISSUE TITLE
Set up remote environment

### ISSUE THREAD

**Issue by ltartari** [okfn-brasil/mosaico#2]
Set heroku environment without database and protected with password (due to the secrecy of the first phase of the project).

**Comment by ltartari** [comment]
Leave the authentication thing to me (I already have some code that I can reuse).

**Comment by vitorbaptista** [comment]
I think we don't need authentication. There's no way for someone to reach the site, unless someone else gives him/her the URL. We're not being linked from anywhere, and Google can't find us.

IMHO, that's enough.

**Comment by ltartari** [comment]
Fair enough. Help me out, @vitorbaptista: what do I need to know in order to sign off this task?

**Comment by vitorbaptista** [comment]
@ltartari I guess checking that we have a deployed application (check http://weiss.herokuapp.com/ and http://weiss-staging.herokuapp.com/) should be enough. This is done.

**Comment by ltartari** [comment]
:+1:

**Comment by ltartari** [comment]
Dev complete.
