### ISSUE TITLE
Back button isn't working

### ISSUE THREAD

**Issue by vitorbaptista** [okfn-brasil/mosaico#35]
The problem is that the treemap's div is positioned over it, so it doesn't get the pointer events.

@ltartari I've assigned you, OK? Shouldn't be difficult.

**Comment by vitorbaptista** [comment]
Before fixing it, think about if we actually need it, now that we have the breadcrumb.

I like the button, but I might be convinced otherwise.

**Comment by ltartari** [comment]
Let's ask what the guys at FGV think about this one. I'm all in for ditching this button : )

**Comment by vitorbaptista** [comment]
@ltartari I think we can close this :+1:

**Comment by ltartari** [comment]
Indeed.
