### ISSUE TITLE
Add spinner to the page whenever we're loading data

### ISSUE THREAD

**Issue by vitorbaptista** [okfn-brasil/mosaico#38]

**Comment by vitorbaptista** [comment]
@ltartari I guess we can close this. To use it, we just need to add async-content to whatever element we want to "disable" while data is loading.

**Comment by ltartari** [comment]
Bravo.

**Comment by andressafioravanti** [comment]
Legal! esta tarefa esta completa. Mas não estou vendo o botão de close por aqui...

**Comment by ltartari** [comment]
Deveria aparecer como "Close & Comment" do lado do botão verde (Comment). Vou fechar por aqui @andressafioravanti ;-)
