### ISSUE TITLE
Breadcrumb slugs are lost when going back

### ISSUE THREAD

**Issue by vitorbaptista** [okfn-brasil/mosaico#41]
## Steps to reproduce
1. Go to a page with some cuts (i.e. http://weiss-staging.herokuapp.com/#/treemap/2013/9-previdencia-social/271-previdencia-basica/33000-ministerio-da-previdencia-social/33201-instituto-nacional-do-seguro-social/90-aplicacoes-diretas)
2. Click on the breadcrumb to go back a few levels, going back to the year (2013), for example;
3. Press the back button in your browser
## Expected

The breadcrumb would be back to what it was before

![image](https://f.cloud.github.com/assets/76945/1211672/1f5ab31a-260d-11e3-83c1-9b8bab53c4c3.png)
## What really happens

The breadcrumb only have the cuts' IDs

![weiss staging herokuapp com treemap 2013 9 previdencia social 271 previdencia basica 33000 ministerio da previdencia social 33201 instituto nacional do seguro social 90 aplicacoes diretas](https://f.cloud.github.com/assets/76945/1211647/b9eb61fa-260c-11e3-9298-6be29829cd98.png)

**Comment by ltartari** [comment]
Damn. :(
![wtf-cat](https://f.cloud.github.com/assets/114248/1211902/8e75b9d6-2610-11e3-97d1-7eed13def484.gif)

**Comment by vitorbaptista** [comment]
Fixed :beers:

**Comment by ltartari** [comment]
![thumbs-up](https://f.cloud.github.com/assets/114248/1249814/1322e322-2ae7-11e3-880e-5256e36fa54e.gif)
