### ISSUE TITLE
When navigating to link with year other than 2013, it redirects to 2013

### ISSUE THREAD

**Issue by vitorbaptista** [okfn-brasil/mosaico#43]
To reproduce, visit http://weiss-staging.herokuapp.com/#/treemap/2012. See that it'll redirect you to http://weiss-staging.herokuapp.com/#/treemap/2013.

**Comment by vitorbaptista** [comment]
Fixed! :dancers:

**Comment by ltartari** [comment]
Great work! ![nice-skills](https://f.cloud.github.com/assets/114248/1249924/2eda2b90-2aea-11e3-8980-c17e072ed1cb.gif)
