### ISSUE TITLE
Breadcrumb for Treemap pages

### ISSUE THREAD

**Issue by ltartari** [okfn-brasil/mosaico#9]

**Comment by vitorbaptista** [comment]
@ltartari I've just finished creating the breadcrumb. IMHO, there's just some design left to close it.

We need to figure out a way to get back to the top level. I guess that's what you wanted the "Treemap" link to be for., but I don't think it's good enough.

Also, when you enter the page with no drilldowns (http://weiss-staging.herokuapp.com/#/treemap/2013), there's no breadcrumb, which is odd.

**Comment by ltartari** [comment]
I'm on it, @vitorbaptista

**Comment by vitorbaptista** [comment]
@ltartari I've added the year as the breadcrumb's first element. It feels a bit redundant now that we have the year dropdown just by its side, but I'm sure it'll get better, when you start building the design.

I did it in part because I like it, but mostly because it's the easiest solution :smile:

**Comment by ltartari** [comment]
Can we replace the link with the <select> for the year on the breadcrumb or that would be asking too much, @vitorbaptista ?

**Comment by vitorbaptista** [comment]
You mean use the dropdown instead of a link for the year? If so, yes, that's asking too much :P

**Comment by vitorbaptista** [comment]
@ltartari Depending on what you think about having the year link as the first element of the breadcrumb, this is dev complete or not :P

**Comment by ltartari** [comment]
Development complete, @vitorbaptista : )

GG

**Comment by andressafioravanti** [comment]
recebi o email do leo falando que some qnd volta... já resolveu isso ?

o que eu reparei é que quando dá voltar e dps avançar ele não descreve o caminho em palavras e sim em códigos.. 

2013 › PREVIDENCIA SOCIAL › 272 › 63000

**Comment by ltartari** [comment]
Abrimos o bug #41 para resolver isso @andressafioravanti

**Comment by andressafioravanti** [comment]
é posível fazer um outro breadcrumb que referenciaria o usuaria a que nível de detalhamento ele está olhando?
se ele tá olhando uma função, uma UO.. etc etc.. 
o que vcs acham da ideia? mt trabalhoso?

**Comment by ltartari** [comment]
@andressafioravanti seria mais referente a todos os contextos do breadcrumb ou somente ao contexto de visualização atual? Exemplo:
Todos os contextos:
`2013 (ANO) › ENCARGOS ESPECIAIS (FUNÇÃO) › SERVICO DA DIVIDA INTERNA (SUBFUNÇÃO) › ENCARGOS FINANCEIROS DA UNIAO (ÓRGÃO)`

Somente o contexto atual:
`2013 › ENCARGOS ESPECIAIS › SERVICO DA DIVIDA INTERNA › ENCARGOS FINANCEIROS DA UNIAO (ÓRGÃO)`

@vitorbaptista qual a complexidade para implementação disso?

**Comment by andressafioravanti** [comment]
Todos. 
Mas pensei que eles estariam dispostos separadamente.

2013 › ENCARGOS ESPECIAIS › SERVICO DA DIVIDA INTERNA › ENCARGOS FINANCEIROS DA UNIAo
2013> Função> Subfunção> Orgão

O que acha?

**Comment by vitorbaptista** [comment]
@andressafioravanti @ltartari É uma ideia interessante (e importante), mas não trivial. Criei a issue #42 para não esquecermos, e podemos priorizá-la na próxima IPM.

**Comment by ltartari** [comment]
Yay! :beers: :+1: :cocktail:
